import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Roboto, Roboto_Mono, Recursive } from "next/font/google";
import "./globals.css";

const robotoSans = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Recursive&display=swap" rel="stylesheet"></link>
      </head>
      <body
        className={`${robotoSans.variable} ${robotoMono.variable} antialiased bg-gray-50 dark:bg-neutral-950`}
      >
        <div className="h-screen flex flex-row">
          {/* Sidebar */}
          <aside className="w-[300px] h-screen bg-white dark:bg-neutral-900 border-r border-gray-200 dark:border-neutral-800 flex flex-col items-center py-6 px-4 gap-6 overflow-hidden">
            {/* Logo (put your lotus SVG here, or temporary text) */}
            <div className="flex items-center justify-center gap-4">
              {/* Logo (spans two rows) */}
              <Image
                src="/satori-logo.svg"
                alt="Satori PageBuilder Logo"
                width={56} // or 64; adjust as desired
                height={56}
                unoptimized
                className="rounded-md"
              />
              {/* Right group: Project name & version */}
              <div className="flex flex-col justify-center h-full">
                <span className="text-2xl font-bold leading-tight text-gray-700">
                  PageBuilder
                </span>
                <span className="text-xs text-gray-500 font-medium font-mono mt-1"
                  style={{
                    letterSpacing: "1px"
                  }}
                >
                  ver 1.0
                </span>
              </div>
            </div>
            {/* (Later: Version Selector Dropdown Here) */}
            {/* Navigation */}
            <nav className="w-full flex-1 flex flex-col gap-1 mt-6">
              {/* Main Sections */}
              <div className="mb-2">
                <a href="#" className="block px-3 py-2 rounded hover:bg-gray-100 dark:hover:bg-neutral-800 font-medium text-gray-800 dark:text-gray-100">
                  Welcome
                </a>
              </div>
              <div className="mb-1">
                <a 
                  href="#" 
                  className="block px-3 py-2 rounded hover:bg-gray-100 dark:hover:bg-neutral-800 font-medium text-gray-800 dark:text-gray-100"
                  style={{
                    letterSpacing: "1px"
                  }}
                >
                  Changelogs
                </a>
                <a 
                  href="#" 
                  className="block px-3 py-2 rounded hover:bg-gray-100 dark:hover:bg-neutral-800 font-medium text-gray-800 dark:text-gray-100"
                  style={{
                    letterSpacing: "1px"
                  }}
                >
                  Quick Start
                </a>
                <a 
                  href="#" 
                  className="block px-3 py-2 rounded hover:bg-gray-100 dark:hover:bg-neutral-800 font-medium text-gray-800 dark:text-gray-100"
                  style={{
                    letterSpacing: "1px"
                  }}
                >
                  Guide
                </a>
                <a 
                  href="#" 
                  className="block px-3 py-2 rounded hover:bg-gray-100 dark:hover:bg-neutral-800 font-medium text-gray-800 dark:text-gray-100"
                  style={{
                    letterSpacing: "1px"
                  }}
                >
                  Known Issues
                </a>
              </div>

              {/* Divider */}
              <div className="h-px my-2 bg-gray-200 dark:bg-neutral-700" />

              {/* API Reference Group */}
              <div>
                <span className="px-3 py-1 text-xs uppercase tracking-widest text-gray-500 dark:text-gray-400 font-bold mb-1 block">
                  API Reference
                </span>
                <a 
                  href="#" 
                  className="block px-3 py-2 rounded hover:bg-gray-100 dark:hover:bg-neutral-800 font-medium text-gray-800 dark:text-gray-100"
                  style={{
                    letterSpacing: "1px"
                  }}
                >
                  Components
                </a>
                <Link 
                  href="/api-reference/interface"
                  className="block px-3 py-2 rounded hover:bg-gray-100 dark:hover:bg-neutral-800 font-medium text-gray-800 dark:text-gray-100"
                  style={{
                    letterSpacing: "1px"
                  }}
                >
                  Interfaces
                </Link>
                <a 
                  href="#" 
                  className="block px-3 py-2 rounded hover:bg-gray-100 dark:hover:bg-neutral-800 font-medium text-gray-800 dark:text-gray-100"
                  style={{
                    letterSpacing: "1px"
                  }}
                >
                  Props Interfaces
                </a>
                <a 
                  href="#" 
                  className="block px-3 py-2 rounded hover:bg-gray-100 dark:hover:bg-neutral-800 font-medium text-gray-800 dark:text-gray-100"
                  style={{
                    letterSpacing: "1px"
                  }}
                >
                  Types &amp; Constants
                </a>
                <a 
                  href="#" 
                  className="block px-3 py-2 rounded hover:bg-gray-100 dark:hover:bg-neutral-800 font-medium text-gray-800 dark:text-gray-100"
                  style={{
                    letterSpacing: "1px"
                  }}
                >
                  Store Classes
                </a>
                <a 
                  href="#" 
                  className="block px-3 py-2 rounded hover:bg-gray-100 dark:hover:bg-neutral-800 font-medium text-gray-800 dark:text-gray-100"
                  style={{
                    letterSpacing: "1px"
                  }}
                >
                  Serialization/Deserialization
                </a>
              </div>

              {/* Divider */}
              <div className="h-px my-2 bg-gray-200 dark:bg-neutral-700" />

              {/* Feedback Section */}
              <div>
                <span className="px-3 py-1 text-xs uppercase tracking-widest text-gray-500 dark:text-gray-400 font-bold mb-1 block">
                  Feedback
                </span>
                <a 
                  href="#" 
                  className="block px-3 py-2 rounded hover:bg-gray-100 dark:hover:bg-neutral-800 font-medium text-gray-800 dark:text-gray-100"
                  style={{
                    letterSpacing: "1px"
                  }}
                >
                  Submit Feedback
                </a>
                <a 
                  href="#" 
                  className="block px-3 py-2 rounded hover:bg-gray-100 dark:hover:bg-neutral-800 font-medium text-gray-800 dark:text-gray-100"
                  style={{
                    letterSpacing: "1px"
                  }}
                >
                  Contact
                </a>
              </div>
            </nav>
          </aside>
          {/* Content Area */}
          <main className="flex-1 overflow-y-auto flex flex-col items-stretch bg-white">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
